security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER_PAID: ROLE_USER
        ROLE_USER_PAID2: ROLE_USER_PAID
        ROLE_TESTER_TRAINING: [ ROLE_USER_PAID2, ROLE_USER_FULL_PROFILE ]
        ROLE_MOD: [ ROLE_USER_PAID2, ROLE_USER_FULL_PROFILE ]
        ROLE_MOD_MAILING: ROLE_MOD
        ROLE_MOD_CONTENT: ROLE_MOD
        ROLE_MOD_PRECHECK_USERS: ROLE_MOD
        ROLE_MOD_PARADOX_USERS: ROLE_MOD
        ROLE_MOD_ADD_USER: ROLE_MOD
        ROLE_MOD_REPRESENTATIVE: ROLE_MOD
        ROLE_MOD_SUPPORT: ROLE_MOD
        ROLE_MOD_FINANCE: ROLE_MOD
        ROLE_MOD_REG_STAT: ROLE_MOD
        ROLE_MOD_API_STAT: ROLE_MOD
        ROLE_MOD_MANAGER: ROLE_MOD
        ROLE_MOD_ACCOUNTANT: ROLE_MOD
        ROLE_ADMIN: [ ROLE_MOD_MAILING, ROLE_MOD_CONTENT, ROLE_MOD_PRECHECK_USERS, ROLE_MOD_PARADOX_USERS, ROLE_MOD_ADD_USER, ROLE_MOD_SUPPORT, ROLE_MOD_FINANCE, ROLE_MOD_REG_STAT, ROLE_MOD_API_STAT, ROLE_MOD_MANAGER, ROLE_MOD_ACCOUNTANT, ROLE_TESTER_TRAINING ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: ~
            anonymous: ~
            remember_me:
                name:     %remember_me.name%
                key:      %secret%
                lifetime: %remember_me.lifetime%
                path:     %remember_me.path%
                domain:   %remember_me.domain%
            switch_user: { role: ROLE_ADMIN, parameter: _user }

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/unsubscribe, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/payments, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/smsru, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cache, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/article, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/check_promo_key, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/captcha, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/confirmation, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pay\-(psb|robokassa)/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER_PAID }
        - { path: ^/admin/, role: ROLE_MOD }
