My\AppBundle\Entity\AttemptsPackage:
    type: entity
    table: attempts
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 256
        number_of_attempts:
            type: integer
        cost:
            type: integer
    oneToMany:
        exam_attempt_logs:
            targetEntity: ExamAttemptLog
            mappedBy: attempts_package
