My\AppBundle\Entity\Image:
    type: entity
    table: images
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        file:
            type: string
            unique: true
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToOne:
        question:
            targetEntity: Question
            inversedBy: image
        category:
            targetEntity: Category
            inversedBy: image
        subject:
            targetEntity: Subject
            inversedBy: image
        flash_block_item:
            targetEntity: FlashBlockItem
            inversedBy: image
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload, removeUploadCache ]
        postRemove: [ removeUpload, removeUploadCache ]
