My\AppBundle\Entity\PromoKey:
    type: entity
    table: promo_key
    repositoryClass: My\AppBundle\Repository\PromoKey
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        active:
            type: boolean
            nullable: true
        created:
            type: datetime
            gedmo:
                timestampable:
                  on: create
        activated:
            type: datetime
            nullable: true
        discount:
            type: integer
        hash:
            type: string
            length: 128
            unique: true
        source:
            type: enumpromokeysource
            nullable: true
        type:
            type: enumservice
            nullable: true
        overdue_letter_num:
            type: integer
            nullable: true
        valid_to:
            type: datetime
            nullable: true
    oneToMany:
        logs:
            targetEntity: \My\PaymentBundle\Entity\Log
            mappedBy: promoKey
        tried_enters:
            targetEntity: My\AppBundle\Entity\TriedEnters
            mappedBy: promo_key
            cascade: ["persist", "remove"]
    manyToOne:
        promo:
            targetEntity: Promo
            inversedBy: keys
            joinColumn:
                name: promo_id
                onDelete: "CASCADE"
                referencedColumnName: id
