My\AppBundle\Entity\Region:
    type: entity
    table: regions
    repositoryClass: My\AppBundle\Repository\RegionRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        discount_1_amount:
            type: integer
        discount_1_date_from:
            type: date
            nullable: true
        discount_1_date_to:
            type: date
            nullable: true
        discount_1_timer_period:
            type: integer
        discount_2_first_amount:
            type: integer
        discount_2_first_days:
            type: integer
        discount_2_second_amount:
            type: integer
        discount_2_second_days:
            type: integer
        discount_2_between_period_days:
            type: integer
        filial_not_existing:
            type: boolean
    oneToMany:
        services_prices:
            targetEntity: ServicePrice
            mappedBy: region
            cascade: [ all ]
        categories_prices:
            targetEntity: CategoryPrice
            mappedBy: region
            cascade: [ all ]
        users:
            targetEntity: User
            mappedBy: region
        places:
            targetEntity: RegionPlace
            mappedBy: region
            cascade: [ all ]
    manyToMany:
        managers:
            targetEntity: My\AppBundle\Entity\User
            mappedBy: manager_regions
