My\AppBundle\Entity\ReservistStat:
    type: entity
    table: reservist_stat
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        type:
            type: boolean
    manyToOne:
        user:
            targetEntity: User
            inversedBy: reservist_stat