My\AppBundle\Entity\Theme:
    type: entity
    table: themes
    repositoryClass: My\AppBundle\Repository\ThemeRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        text:
            type: text
            nullable: true
        position:
            type: integer
            gedmo:
                - sortablePosition
    oneToOne:
        slice:
            targetEntity: Slice
            mappedBy: after_theme
    oneToMany:
        questions:
            targetEntity: Question
            mappedBy: theme
        tests_logs:
            targetEntity: ThemeTestLog
            mappedBy: theme
        readers:
            targetEntity: My\AppBundle\Entity\ThemeReader
            mappedBy: theme
    manyToOne:
        subject:
            targetEntity: Subject
            inversedBy: themes
            gedmo:
                - sortableGroup
    manyToMany:
        versions:
            targetEntity: TrainingVersion
            inversedBy: themes
            joinTable:
                name: training_versions_themes
                joinColumns:
                    theme_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    version_id:
                        referencedColumnName: id
