<?php

namespace My\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DrivingPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrivingPackageRepository extends EntityRepository
{
    public function getNotSaleAndNotRezervPackages($drvCondition = null, $user = null)
    {
        $currentTime = new \DateTime();
        $findDateTime = $currentTime->sub(new \DateInterval('PT2H'));
        $qb = $this->createQueryBuilder('p')
            ->andWhere('p.sale_at IS NULL')
            ->andWhere('p.rezerv_at IS NULL OR p.rezerv_at <= :time OR (p.rezerv_at > :time AND p.user = :user)')
            ->setParameter('time', $findDateTime)
            ->setParameter('user', $user)
        ;

        if (isset($drvCondition)) {
            $qb->andWhere('p.condition = :drv_condition')->setParameter('drv_condition', $drvCondition);
        }

        return $qb->getQuery()->execute();
    }
}
