<?php

namespace My\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SettingAutoCreatePromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingAutoCreatePromoRepository extends EntityRepository
{
    protected $settings = array();
    
    /**
     * @return array
     */
    public function getAllData()
    {
        $settings = $this->findAll();
        foreach ($settings as $setting) {
            /** @var $setting \My\AppBundle\Entity\SettingAutoCreatePromo */
            $value = $setting->getValue();

            settype($value, $setting->getType() ? $setting->getType() : 'string');
            $this->settings[$setting->getKey()] = $value;
        }
        
        return $this->settings;
    }
}
